### ISSUE TITLE
`xenon.relocated.io.grpc.StatusRuntimeException: INTERNAL: Unable to parse request`

### ISSUE THREAD

**Issue by camper42** [housepower/spark-clickhouse-connector#154]
error log:
```
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 4) (10.113.41.152 executor 2): xenon.relocated.io.grpc.StatusRuntimeException: INTERNAL:
 Unable to parse request
        at xenon.relocated.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
        at xenon.relocated.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
        at xenon.relocated.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
        at xenon.protocol.grpc.ClickHouseGrpc$ClickHouseBlockingStub.executeQuery(ClickHouseGrpc.java:316)
        at xenon.clickhouse.grpc.GrpcNodeClient.executeQuery(GrpcNodeClient.scala:184)
        at xenon.clickhouse.grpc.GrpcNodeClient.syncInsert(GrpcNodeClient.scala:150)
        at xenon.clickhouse.grpc.GrpcNodeClient.syncInsertOutputJSONEachRow(GrpcNodeClient.scala:115)
        at xenon.clickhouse.write.ClickHouseWriter.$anonfun$flush$1(ClickHouseWriter.scala:159)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.Try$.apply(Try.scala:213)
        at xenon.clickhouse.Utils$.retry(Utils.scala:83)
        at xenon.clickhouse.write.ClickHouseWriter.flush(ClickHouseWriter.scala:143)
        at xenon.clickhouse.write.ClickHouseWriter.commit(ClickHouseWriter.scala:96)
        at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.$anonfun$run$1(WriteToDataSourceV2Exec.scala:430)
        at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1496)
        at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:457)
        at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:358)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

reproduce:

1. create table in clickhouse
```
create table dev.error (age Long, name String) ENGINE =  TinyLog();
```

2. use latest snapshot
```
pyspark --repositories https://oss.sonatype.org/content/repositories/snapshots --packages com.github.housepower:clickhouse-spark-runtime-3.2_2.12:0.4.0-SNAPSHOT
```
```
❯ md5sum com.github.housepower_clickhouse-spark-runtime-3.2_2.12-0.4.0-SNAPSHOT.jar
26642b8172159b05a7d1748dc47e764c  com.github.housepower_clickhouse-spark-runtime-3.2_2.12-0.4.0-SNAPSHOT.jar
```

3. write to clickhouse
```
df = spark.read.json("/usr/local/spark/examples/src/main/resources/people.json")
df.writeTo("`ck-1`.dev.error").append()
```

---

something wrong after #153

**Comment by camper42** [comment]
seems related to clickhouse version

```
export CLICKHOUSE_IMAGE=clickhouse/clickhouse-server:21.8.12.29
./gradlew clean test --tests=ClickHouseSingleSuite
```

**Comment by camper42** [comment]
```
query: "INSERT INTO `db_part_date`.`tbl_part_date` FORMAT JSONEachRow"
query_id: "409c1288-c470-4ea9-8592-364ffa67dd4a"
input_data: "\004\"M\030`ps\036\000\000\200{\"id\":11,\"date\":\"2022-04-11\"}\n\000\000\000\000"
output_format: "JSONEachRow"
user_name: "default"
input_compression_type: "lz4"
```

bad input_data ?

**Comment by pan3793** [comment]
It may be caused by https://github.com/ClickHouse/ClickHouse/pull/34408

Try set `spark.clickhouse.write.compression.codec=none`

**Comment by camper42** [comment]
> Try set spark.clickhouse.write.compression.codec=none

It works, thx
