### ISSUE TITLE
read error `Unknown format JSONCompactEachRowWithNamesAndTypes` when use with tcp protocol (clickhouse-cli-client)

### ISSUE THREAD

**Issue by camper42** [housepower/spark-clickhouse-connector#257]
when use with http protocol, many of our write job need to set `spark.clickhouse.write.batchSize` lower than 200 to avoid `Error writing request body to server`, and performance is really bad.

we try to use tcp protocol with clickhouse-cli-client, write performance looks good, but we read clickhouse is broken.

```
23/07/13 17:01:15 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0) (10.113.7.93 executor 17): xenon.clickhouse.exception.CHServerException: [TCP]default@IPADDRESS:9000}/default [73] Code: 73. DB::Exception: Unknown format JSONCompactEachRowWithNamesAndTypes
, server ClickHouseNode [uri=tcp://IPADDRESS:9000/default]@-1683826906
	at xenon.clickhouse.client.NodeClient.queryAndCheck(NodeClient.scala:176)
	at xenon.clickhouse.read.ClickHouseReader.resp$lzycompute(ClickHouseReader.scala:68)
	at xenon.clickhouse.read.ClickHouseReader.resp(ClickHouseReader.scala:68)
	at xenon.clickhouse.read.format.ClickHouseJsonReader.streamOutput$lzycompute(ClickHouseJsonReader.scala:41)
	at xenon.clickhouse.read.format.ClickHouseJsonReader.streamOutput(ClickHouseJsonReader.scala:40)
	at xenon.clickhouse.read.format.ClickHouseJsonReader.streamOutput(ClickHouseJsonReader.scala:33)
	at xenon.clickhouse.read.ClickHouseReader.next(ClickHouseReader.scala:84)
	at org.apache.spark.sql.execution.datasources.v2.PartitionIterator.hasNext(DataSourceRDD.scala:120)
	at org.apache.spark.sql.execution.datasources.v2.MetricsIterator.hasNext(DataSourceRDD.scala:158)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.$anonfun$hasNext$1(DataSourceRDD.scala:63)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.$anonfun$hasNext$1$adapted(DataSourceRDD.scala:63)
	at scala.Option.exists(Option.scala:376)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.hasNext(DataSourceRDD.scala:63)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.advanceToNextIter(DataSourceRDD.scala:97)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.hasNext(DataSourceRDD.scala:63)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.hashAgg_doAggregateWithKeys_1$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.hashAgg_doAggregateWithKeys_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.sort_addToSorter_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
	at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.$anonfun$run$1(WriteToDataSourceV2Exec.scala:464)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1563)
	at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.run(WriteToDataSourceV2Exec.scala:509)
	at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.run$(WriteToDataSourceV2Exec.scala:448)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:514)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:411)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:92)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
	at org.apache.spark.scheduler.Task.run(Task.scala:139)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:554)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1529)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:557)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: org.apache.spark.util.TaskCompletionListenerException: [TCP]default@IPADDRESS:9000}/default [73] Code: 73. DB::Exception: Unknown format JSONCompactEachRowWithNamesAndTypes

, server ClickHouseNode [uri=tcp://IPADDRESS:9000/default]@-1683826906
```

**Comment by camper42** [comment]
when set `spark.clickhouse.read.format` to `binary`:

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (10.113.6.250 executor 1): xenon.clickhouse.exception.CHServerException: [TCP]default@IPADDRESS:9000}/default [73] Code: 73. DB::Exception: Unknown format RowBinaryWithNamesAndTypes

, server ClickHouseNode [uri=tcp://IPADDRESS:9000/default]@-1985448283
	at xenon.clickhouse.client.NodeClient.queryAndCheck(NodeClient.scala:176)
	at xenon.clickhouse.read.ClickHouseReader.resp$lzycompute(ClickHouseReader.scala:68)
	at xenon.clickhouse.read.ClickHouseReader.resp(ClickHouseReader.scala:68)
	at xenon.clickhouse.read.format.ClickHouseBinaryReader.streamOutput$lzycompute(ClickHouseBinaryReader.scala:36)
	at xenon.clickhouse.read.format.ClickHouseBinaryReader.streamOutput(ClickHouseBinaryReader.scala:36)
	at xenon.clickhouse.read.ClickHouseReader.next(ClickHouseReader.scala:84)
	at org.apache.spark.sql.execution.datasources.v2.PartitionIterator.hasNext(DataSourceRDD.scala:120)
	at org.apache.spark.sql.execution.datasources.v2.MetricsIterator.hasNext(DataSourceRDD.scala:158)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.$anonfun$hasNext$1(DataSourceRDD.scala:63)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.$anonfun$hasNext$1$adapted(DataSourceRDD.scala:63)
	at scala.Option.exists(Option.scala:376)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.hasNext(DataSourceRDD.scala:63)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.advanceToNextIter(DataSourceRDD.scala:97)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.hasNext(DataSourceRDD.scala:63)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:888)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:888)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:92)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
	at org.apache.spark.scheduler.Task.run(Task.scala:139)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:554)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1529)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:557)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: org.apache.spark.util.TaskCompletionListenerException: [TCP]default@IPADDRESS:9000}/default [73] Code: 73. DB::Exception: Unknown format RowBinaryWithNamesAndTypes

, server ClickHouseNode [uri=tcp://IPADDRESS:9000/default]@-1985448283
```

**Comment by pan3793** [comment]
Before looking into the error with the TCP protocol, I suppose the HTTP protocol should be good with the large batch size on writing. cc @zhicwu do you have suggestions about the `Error writing request body to server`?

**Comment by camper42** [comment]
I'm not sure if it's our cluster version(21.8.12.29) or the data characteristics(long string or whatever) that are causing the `Error writing request body to server`

problem start after switching from grpc to http (upgrade from 0.4.0), I'll try to get more info later

**Comment by camper42** [comment]
seems like https://github.com/ClickHouse/clickhouse-java/issues/1379

we using Clickhouse nodes directly and current `keep_alive_timeout` is 120, I'll try to increase it

**Comment by camper42** [comment]
still have problem with server `keep_alive_timeout=600`, and no exceptions in the `system.query_log`

**Comment by zhicwu** [comment]
> still have problem with server keep_alive_timeout=600, and no exceptions in the system.query_log

Is there any proxy between client and server? You may add `use_no_proxy=true` in connection string to ensure that.

> when use with http protocol, many of our write job need to set spark.clickhouse.write.batchSize lower than 200 to avoid Error writing request body to server, and performance is really bad.

Perhaps you can check the exact insert statement logged in `system.query_log`. Is it a large string with `VALUES` expression or something like `insert into mytable(columns) format RowBinary`? Usually the latter is faster. Increasing `request_chunk_size` may help too as I recalled.

**Comment by camper42** [comment]
> Is there any proxy between client and server? You may add use_no_proxy=true in connection string to ensure that.
No proxy between client and server
connection string build by spark-clickhouse-connector, no way to add `use_no_proxy=true` on my side ?

> Is it a large string with VALUES expression or something like insert into mytable(columns) format RowBinary

in `system.query_log`, we have query like ```INSERT INTO `db`.`table` FORMAT ArrowStream``` or ```INSERT INTO `db`.`table` FORMAT JSONEachRow```

> Increasing request_chunk_size may help too as I recalled.

https://github.com/housepower/spark-clickhouse-connector/blob/master/clickhouse-core/src/main/scala/xenon/clickhouse/client/NodeClient.scala#L45 no way to set `request_chunk_size` in spark-clickhouse-connector ?

**Comment by pan3793** [comment]
> no way to set `request_chunk_size` in spark-clickhouse-connector ?

Emm... you can hardcode directly to verify if it works, we can make it configurable then.

**Comment by camper42** [comment]
after inspect the code, seems `spark.sql.catalog.clickhouse.option.request_chunk_size` could set the option we need.

`[1002] Error writing request body to server, server ClickHouseNode [uri=http://IP:8123/default, options={use_no_proxy=true}]`

`[1002] Error writing request body to server, server ClickHouseNode [uri=http://IP:8123/default, options={request_chunk_size=40960,use_no_proxy=true}]`

`[1002] Unknown error 1002, server ClickHouseNode [uri=http://IP:8123/default, options={request_chunk_size=1048576,use_no_proxy=true}]`

`[1002] Unknown error 1002, server ClickHouseNode [uri=http://IP:8123/default, options={max_buffer_size=1048576,request_chunk_size=1048576,use_no_proxy=true}]`

**Comment by pan3793** [comment]
Yes, it's allowed to set additional request options via 
```
spark.sql.catalog.clickhouse.option.<request_option_key>=<value>
```

**Comment by camper42** [comment]
in `system.query_log`, I found some QueryFinish with `written_rows!=results_rows` , no `exception` and `exception_code=0`. Does this correspond to unknown error 1002? @zhicwu @pan3793 

The difference between these queries is that the thread_ids column has multiple values, whereas the other `written_rows==result_rows` query thread_ids has only one value.

![image](https://github.com/housepower/spark-clickhouse-connector/assets/3177898/b752e71d-ed20-4b82-874b-c38d088e761b)

**Comment by camper42** [comment]
root exception is `java.io.IOException` in `com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse` and I didn't post above.

```
23/07/17 19:14:41 WARN TaskSetManager: Lost task 4.0 in stage 0.0 (TID 4) (IPaddress executor 2): xenon.clickhouse.exception.CHServerException: [HTTP]default@IPaddress:8123}/default [1002] Unknown error 1002, server ClickHouseNode [uri=http://IPaddress:8123/default, options={max_buffer_size=1048576,request_chunk_size=1048576,use_no_proxy=true}]@-335926745
	at xenon.clickhouse.client.NodeClient.syncInsert(NodeClient.scala:121)
	at xenon.clickhouse.client.NodeClient.syncInsertOutputJSONEachRow(NodeClient.scala:86)
	at xenon.clickhouse.write.ClickHouseWriter.$anonfun$doFlush$1(ClickHouseWriter.scala:232)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at xenon.clickhouse.Utils$.retry(Utils.scala:86)
	at xenon.clickhouse.write.ClickHouseWriter.doFlush(ClickHouseWriter.scala:230)
	at xenon.clickhouse.write.ClickHouseWriter.flush(ClickHouseWriter.scala:220)
	at xenon.clickhouse.write.ClickHouseWriter.write(ClickHouseWriter.scala:192)
	at xenon.clickhouse.write.ClickHouseWriter.write(ClickHouseWriter.scala:39)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.write(WriteToDataSourceV2Exec.scala:516)
	at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.$anonfun$run$1(WriteToDataSourceV2Exec.scala:471)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1563)
	at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.run(WriteToDataSourceV2Exec.scala:509)
	at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.run$(WriteToDataSourceV2Exec.scala:448)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:514)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:411)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:92)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
	at org.apache.spark.scheduler.Task.run(Task.scala:139)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:554)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1529)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:557)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.clickhouse.client.ClickHouseException: Unknown error 1002, server ClickHouseNode [uri=http://IPaddress:8123/default, options={max_buffer_size=1048576,request_chunk_size=1048576,use_no_proxy=true}]@-335926745
	at com.clickhouse.client.ClickHouseException.of(ClickHouseException.java:168)
	at com.clickhouse.client.AbstractClient.lambda$execute$0(AbstractClient.java:275)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 3 more
Caused by: java.io.IOException:
	at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:184)
	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:227)
	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:124)
	at com.clickhouse.client.AbstractClient.sendAsync(AbstractClient.java:161)
	at com.clickhouse.client.AbstractClient.lambda$execute$0(AbstractClient.java:273)
	... 4 more
```

**Comment by camper42** [comment]
with
- `spark.sql.catalog.clickhouse.option.use_no_proxy=true`
- `spark.sql.catalog.clickhouse.option.buffer_size=131072` (default max buffer size)
- `spark.clickhouse.write.batchSize=10000`

when use `HTTP_URL_CONNECTION` 2/3 run sucess, 1 has two tasks failed with `[1002] Error writing request body to server`
when use `APACHE_HTTP_CLIENT` 2/3 run success, 1 has a task failed with `[1002] Error writing request body to server`
when use `HTTP_CLIENT` 4/4 run success

much better than before, and the failed task seems doesn't cause duplicate write as we presume

**Comment by zhicwu** [comment]
> in system.query_log, I found some QueryFinish with written_rows!=results_rows , no exception and exception_code=0. Does this correspond to unknown error 1002?

CH 21.8 is no longer supported, so perhaps you should try to upgrade to LTS version like 22.8 or 22.3? If you have to stay on the same version, you may also want to check server log files to see if there's additional information.

Please also consider to enable transaction support(:warning: experimental feature), so that retries can be performed safely without concern for duplicating data or losing data.

> when use `HTTP_CLIENT` 4/4 run success

This is odd. Either `APACHE_HTTP_CLIENT` or `HTTP_CLIENT` never survives in stress test, as they always ended up with a few failures, which is why `HTTP_URL_CONNECTION` is still the default. Just want to double check, are you using clickhouse-jdbc v0.4.6?

**Comment by camper42** [comment]
> CH 21.8 is no longer supported, so perhaps you should try to upgrade to LTS version like 22.8 or 22.3? If you have to stay on the same version, you may also want to check server log files to see if there's additional information.

our CH is a cloud service, so we can't see the log files. I will advise my team to upgrade to 22.8 as soon as possible.

> Just want to double check, are you using clickhouse-jdbc v0.4.6?

v0.4.5, I don't think our write load is higher than the stress test, and I would have expected `http_connection_provider` not to make any difference 😂

**Comment by camper42** [comment]
one of our cluster upgrade to 22.8, add `spark.sql.catalog.clickhouse.option.custom_http_params async_insert=1,wait_for_async_insert=1` to `spark-defaults.conf`

no error with batchSize 10000, and performance is good.
