### ISSUE TITLE
Failed to query fields of type FixedString

### ISSUE THREAD

**Issue by eye-gu** [housepower/spark-clickhouse-connector#264]
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot access contents of TextNode as binary due to broken Base64 encoding: Unexpected end of base64-encoded String: base64 variant 'MIME-NO-LINEFEEDS' expects padding (one or more '=' characters) at the end. This Base64Variant might have been incorrectly configured
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.node.TextNode.getBinaryValue(TextNode.java:78)
	at com.fasterxml.jackson.databind.node.TextNode.binaryValue(TextNode.java:89)
	at xenon.clickhouse.read.format.ClickHouseJsonReader.decodeValue(ClickHouseJsonReader.scala:81)
	at xenon.clickhouse.read.format.ClickHouseJsonReader.decode(ClickHouseJsonReader.scala:48)
	at xenon.clickhouse.read.format.ClickHouseJsonReader.decode(ClickHouseJsonReader.scala:33)
	at xenon.clickhouse.read.ClickHouseReader.get(ClickHouseReader.scala:89)
	at xenon.clickhouse.read.ClickHouseReader.get(ClickHouseReader.scala:29)

**Comment by pan3793** [comment]
Seems like you are storing binary data instead of UTF-8 encoded string using FixedString, mind providing more details about your use case and failed queries?

**Comment by eye-gu** [comment]
![image](https://github.com/housepower/spark-clickhouse-connector/assets/20450037/61e66fcc-0a18-4d8c-84bc-41654ee6a8d5)
![image](https://github.com/housepower/spark-clickhouse-connector/assets/20450037/2aae8fd3-3757-44af-be3f-49297e7067e4)

DBeaver sql : SELECT column_fixedString from zhouwq.alltype;
spark sql : select column_fixedString from clickhouse.zhouwq.alltype;
spark version: spark-3.3.0-bin-hadoop2
`column_fixedString` of type `FixedString(2)` data is all `ab`

**Comment by eye-gu** [comment]
I found that in the 'fromClickHouseType' method, the 'FixedString' type is mapped to a 'BinaryType', why is it not a 'StringType'?

**Comment by pan3793** [comment]
technically, ClickHouse's FixedString and String are allowed to store any bytes, seems we need to make the type mapping configurable

**Comment by harryshi10** [comment]
made a [PR](https://github.com/housepower/spark-clickhouse-connector/pull/317) for this
